### ISSUE TITLE
Unable to open settings on v10

### ISSUE THREAD

**Issue by Gawdl3y** [ardittristan/HookMacros#8]
When attempting to open the Hook Macros settings window in v10, the following exception occurs:
```
TypeError: Cannot read properties of undefined (reading 'includes')
[Detected 1 package: launchmacro]
    at HookSettingsApplication.getData (hookmacro.js:151:38)
    at HookSettingsApplication._render (foundry.js:4959:29)
    at HookSettingsApplication._render (foundry.js:5684:17)
    at HookSettingsApplication.render (foundry.js:4918:10)
    at MonksSettingsConfig._onClickSubmenu (foundry.js:70865:16)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

The exception occurs at [this line](https://github.com/ardittristan/HookMacros/blob/master/hookmacro.js#L151) because `game.data.version` is undefined.

**Comment by toastygm** [comment]
Yeah, the problem is it is using `game.data.version` instead of `game.system.version`.  Just change `data` to `system` at line 151 in `hookmacro.js`and it should work.
